# Generated by Django 4.2.8 on 2023-12-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='client_id'),
        ),
    ]
