# Generated by Django 4.2.8 on 2023-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_clients_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_id',
            field=models.IntegerField(verbose_name='client_id'),
        ),
    ]
